{
  "openapi": "3.0.0",
  "info": {
    "title": "Enrutador API",
    "description": "API del flujo de pago de servicios para el middleware",
    "version": "0.1.9"
  },
  "servers": [
    {
      "url": "http://{base_url}:{port}/{base_path}",
      "description": "Staging server",
      "variables": {
        "base_url": {
          "default": "172.16.1.32"
        },
        "port": {
          "default": "8087"
        },
        "base_path": {
          "default": ""
        }
      }
    }
  ],
  "paths": {
    "/criteriosbusquedas": {
      "post": {
        "description": "Criterios de busquedas",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/searchCriteriaRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully sent"
          },
          "400": {
            "$ref": "#/components/responses/400Error"
          }
        }
      }
    },
    "/clientes": {
      "post": {
        "description": "Clientes",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/clientRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully sent"
          },
          "400": {
            "$ref": "#/components/responses/400Error"
          }
        }
      }
    },
    "/deudas": {
      "post": {
        "description": "Deudas",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/debtsRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully sent"
          },
          "400": {
            "$ref": "#/components/responses/400Error"
          }
        }
      }
    },
    "/pagos": {
      "post": {
        "description": "Pagos",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/paymentsRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully sent"
          },
          "400": {
            "$ref": "#/components/responses/400Error"
          }
        }
      }
    },
    "/documentos": {
      "post": {
        "description": "Documentos",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/documentsRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully sent"
          },
          "400": {
            "$ref": "#/components/responses/400Error"
          }
        }
      }
    }
  },
  
  "components": {
    "schemas": {
      "searchCriteriaRequest": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/searchCriteriaData"
          },
          "metadata": {
            "$ref": "#/components/schemas/metadata"
          }
        }
      },
      "clientRequest": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/clientData"
          },
          "metadata": {
            "$ref": "#/components/schemas/metadata"
          }
        }
      },
      "debtsRequest": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/debtsData"
          },
          "metadata": {
            "$ref": "#/components/schemas/metadata"
          }
        }
      },
      "paymentsRequest": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/paymentsData"
          },
          "metadata": {
            "$ref": "#/components/schemas/metadata"
          }
        }
      },
      "documentsRequest": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/documentsData"
          },
          "metadata": {
            "$ref": "#/components/schemas/metadata"
          }
        }
      },
      "searchCriteriaData": {
        "type": "object",
        "properties": {
          "serviceId": {
            "type": "number",
            "decription": "service code",
            "example": "624"
          },
          "type": {
            "type": "string",
            "decription": "method type",
            "example": "B"
          }
        }
      },
      "clientData": {
        "type": "object",
        "properties": {
          "serviceId": {
            "type": "number",
            "decription": "service code",
            "example": "623"
          },
          "filtro": {
            "$ref": "#/components/schemas/ArrayOfFilters"
          }                       
            
        }
      },
      "debtsData": {
        "type": "object",
        "properties": {
          "serviceId": {
            "type": "number",
            "decription": "service code",
            "example": "623"
          },
          "filtro": {
            "$ref": "#/components/schemas/ArrayOfDebts"
          }                       
            
        }
      },
      "paymentsData": {
        "type": "object",
        "properties": {
          "serviceId": {
            "type": "number",
            "decription": "service code",
            "example": "631"
          },
          "filtro": {
            "$ref": "#/components/schemas/ArrayOfPaymentsFilter"
          }, 
          "deuda": {
            "$ref": "#/components/schemas/ArrayOfPaymentsFilter"
          }                        
            
        }
      },
      "documentsData": {
        "type": "object",
        "properties": {
          "serviceId": {
            "type": "number",
            "decription": "service code",
            "example": "628"
          },
          "filtro": {
            "$ref": "#/components/schemas/ArrayOfDocuments"
          }                       
            
        }
      },
      "ArrayOfFilters": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "identificador": {
              "type": "integer"
            },
            "alias": {
              "type": "string"
            },
            "valor": {
              "type": "string"
            }
          }
        },
        "example": [
          {
            "dentificador": 3,
            "alias": "3230",
            "valor": "12345"
          },
          {
            "identificador": 2,
            "alias": "3235",
            "valor": "12345"
          }
        ]
      },
      "ArrayOfDebts": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "identificador": {
              "label": "string"
            },
            "value": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "editable": {
              "type": "string"
            },
          
            "description": {
              "type": "string"
            },
            "code": {
              "type": "string"
            }
          }
        },
        "example": [
          {
            "label": "3230",
            "value": "12345",
            "mandatory": true,
            "editable": "N",
            "description": "ID CODIGO",
            "code": "identificador"
          },
          {
            "label": "3235",
            "value": "12345",
            "mandatory": true,
            "editable": "N",
            "description": "ID SERVICIO ",
            "code": "identificador2"
          }
        ]
      },
      "ArrayOfPaymentsFilter": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "identificador": {
              "label": "string"
            },
            "value": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "editable": {
              "type": "string"
            },
            "grupo": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "code": {
              "type": "string"
            }
          }
        },
        "example": [
          {
            "label": "codigoClienteEmpresa",
            "value": "39",
            "mandatory": true,
            "editable": "N",
            "grupo": "filtro",
            "description": "",
            "code": ""
        },
        {
            "label": "empresa",
            "value": "47",
            "mandatory": true,
            "editable": "N",
            "grupo": "filtro",
            "description": "",
            "code": ""
        },
        {
            "label": "nombre",
            "value": "Vallejos Salda√±a Oscar",
            "mandatory": true,
            "editable": "N",
            "grupo": "filtro",
            "description": "",
            "code": ""
        },
        {
            "label": "Nit",
            "value": "5354698",
            "mandatory": true,
            "editable": "N",
            "grupo": "filtro",
            "description": "",
            "code": ""
        },
        {
            "label": "telefono",
            "value": "-1",
            "mandatory": true,
            "editable": "N",
            "grupo": "filtro",
            "description": "",
            "code": ""
        },
        {
            "label": "tnCliente",
            "value": "32",
            "mandatory": true,
            "editable": "N",
            "grupo": "filtro",
            "description": "",
            "code": ""
        },
        {
            "label": "tnTransaccion",
            "value": "81",
            "mandatory": true,
            "editable": "N",
            "grupo": "filtro",
            "description": "",
            "code": ""
        },
        {
            "label": "tcCorreoEnvio",
            "value": "juan@hotmail.com",
            "mandatory": true,
            "editable": "S",
            "grupo": "filtro",
            "description": "",
            "code": ""
        },
        {
            "label": "tnTelefonoEnvio",
            "value": "78091091",
            "mandatory": true,
            "editable": "S",
            "grupo": "filtro",
            "description": "",
            "code": ""
        }
        ]
      },
      "ArrayOfPaymentsDebt": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "identificador": {
              "label": "string"
            },
            "value": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "editable": {
              "type": "string"
            },
            "grupo": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "code": {
              "type": "string"
            }
          }
        },
        "example": [
          {
            "label": "factura",
            "value": "3170173",
            "mandatory": true,
            "editable": "N",
            "grupo": "deuda",
            "description": "",
            "code": ""
          },
          {
              "label": "periodo",
              "value": "2021-07",
              "mandatory": true,
              "editable": "N",
              "grupo": "deuda",
              "description": "",
              "code": ""
          },
          {
              "label": "monto",
              "value": "52.18",
              "mandatory": true,
              "editable": "N",
              "grupo": "deuda",
              "description": "",
              "code": ""
          },
          {
              "label": "comision",
              "value": "0",
              "mandatory": true,
              "editable": "N",
              "grupo": "deuda",
              "description": "",
              "code": ""
          }
        ]
      },

      "ArrayOfDocuments": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "identificador": {
              "label": "string"
            },
            "value": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "editable": {
              "type": "string"
            },
            "grupo": {
              "type": "string"
            }
          }
        },
        "example": [
          {
            "label": "factura",
            "value": "23640409",
              "mandatory": true,
              "editable": "N",
              "grupo": "filtro"
          },
          {
              "label": "tipo",
              "value": "",
              "mandatory": true,
              "editable": "N",
              "grupo": "filtro"
          }
        ]
      },
      "metadata": {
        "type": "object",
        "description": "metadata",
        "required": [
          "codUsuario",
          "codSucursal",
          "codAplicacion"
        ],
        "properties": {
          "codUsuario": {
            "type": "string",
            "decription": "user code",
            "example": "JBK"
          },
          "codSucursal": {
            "type": "integer",
            "decription": "branch number",
            "example": 1
          },
          "codAplicacion": {
            "type": "integer",
            "decription": "application code",
            "example": 7
          }
        }
      }
    },
    "responses": {
      "400Error": {
        "description": "Invalid request",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}